"""email_confirmed for users

Revision ID: 7699ebc8292d
Revises: 0d91a85e4a73
Create Date: 2024-04-24 11:03:47.640965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7699ebc8292d'
down_revision: Union[str, None] = '0d91a85e4a73'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_confirmed')
    # ### end Alembic commands ###
